# Generated by Django 4.2.1 on 2023-06-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_rooms_disponible_remove_rooms_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto_arr',
            fields=[
                ('timefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.timefield')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('polls.timefield',),
        ),
    ]
