# Generated by Django 4.2.1 on 2023-06-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_gastosarr_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UM_arr',
            fields=[
                ('timefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.timefield')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('polls.timefield',),
        ),
        migrations.AlterField(
            model_name='gastosarr',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.um_arr'),
        ),
    ]
