# Generated by Django 4.2.1 on 2023-06-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_um_arr_alter_gastosarr_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto_esp',
            fields=[
                ('timefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.timefield')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('polls.timefield',),
        ),
        migrations.CreateModel(
            name='UM_esp',
            fields=[
                ('timefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.timefield')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('polls.timefield',),
        ),
        migrations.AlterField(
            model_name='gastosespacio',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.concepto_esp'),
        ),
        migrations.AlterField(
            model_name='gastosespacio',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.um_esp'),
        ),
    ]
